from slop_code.entrypoints.commands import backfill_categories
from slop_code.entrypoints.commands import backfill_reports
from slop_code.entrypoints.commands import carry_forward
from slop_code.entrypoints.commands import combine_results
from slop_code.entrypoints.commands import compress_artifacts
from slop_code.entrypoints.commands import consolidate_runs
from slop_code.entrypoints.commands import docker
from slop_code.entrypoints.commands import eval_checkpoint
from slop_code.entrypoints.commands import eval_problem_dir
from slop_code.entrypoints.commands import eval_run_dir
from slop_code.entrypoints.commands import infer_problem
from slop_code.entrypoints.commands import judge
from slop_code.entrypoints.commands import make_registry
from slop_code.entrypoints.commands import migrate_evaluation_format
from slop_code.entrypoints.commands import problems
from slop_code.entrypoints.commands import render_prompts
from slop_code.entrypoints.commands import repopulate_diffs
from slop_code.entrypoints.commands import repopulate_diffstats
from slop_code.entrypoints.commands import run_agent
from slop_code.entrypoints.commands import static
from slop_code.entrypoints.commands import sync
from slop_code.entrypoints.commands import tools
from slop_code.entrypoints.commands import variance
from slop_code.entrypoints.commands import viz
